name: subh_warrior
description: Subh Warrior Challenge app to build powerful morning routines with Fajr prayer and productive work.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.5+1

  # Local Storage
  shared_preferences: ^2.5.3

  # Firebase
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2

  # Location & Prayer Times
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  http: ^1.5.0

  # UI Components
  percent_indicator: ^4.2.5
  fl_chart: ^0.65.0

  # Utilities
  intl: ^0.20.2
  flutter_timezone: ^5.0.0

  # Notifications
  flutter_local_notifications: ^19.4.2

  # Calendar
  table_calendar: ^3.2.0

  # Network
  connectivity_plus: ^7.0.0
  cached_network_image: ^3.4.1

  # Icons
  flutter_svg: ^2.2.1
  font_awesome_flutter: ^10.9.1

  # Permissions
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true