// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA781rpTGOKTbFnB8VVWPfHe2c6tC4YaQ',
    appId: '1:798483347271:web:0bd4ff31dda3600a00be62',
    messagingSenderId: '798483347271',
    projectId: 'subh-warrior',
    authDomain: 'subh-warrior.firebaseapp.com',
    storageBucket: 'subh-warrior.firebasestorage.app',
    measurementId: 'G-FK03G5KXKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB68s1VhzCPi-2yw_bnTvx0L3SXP0Onokg',
    appId: '1:798483347271:android:31a48769e52c3fad00be62',
    messagingSenderId: '798483347271',
    projectId: 'subh-warrior',
    storageBucket: 'subh-warrior.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3rYfakebwxihX4llQj5W8k3RlW5XxpBA',
    appId: '1:798483347271:ios:eb1e50f856b729b800be62',
    messagingSenderId: '798483347271',
    projectId: 'subh-warrior',
    storageBucket: 'subh-warrior.firebasestorage.app',
    iosBundleId: 'com.subhwarrior.app',
  );
}
